### ISSUE TITLE
Running Error

### ISSUE THREAD

**Issue by BruceChen2017** [CityBrainChallenge/KDDCup2021-CityBrainChallenge-starter-kit#1]
When running `python3 demo.py`, it gives me error:  
```
Traceback (most recent call last):
  File "demo.py", line 13, in <module>
    gym_dict=gym_cfg_instance.cfg
  File "/usr/local/lib/python3.7/dist-packages/gym/envs/registration.py", line 145, in make
    return registry.make(id, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/gym/envs/registration.py", line 90, in make
    env = spec.make(**kwargs)
  File "/usr/local/lib/python3.7/dist-packages/gym/envs/registration.py", line 60, in make
    env = cls(**_kwargs)
  File "/usr/local/lib/python3.7/dist-packages/CBEngine/envs/CBEngine.py", line 18, in __init__
    self.eng = citypb.Engine(self.simulator_cfg_file,thread_num)
IndexError: basic_string::at: __n (which is 18446744073709551615) >= this->size() (which is 2)
```

**Comment by zhyliu00** [comment]
Thanks for your comment. Incorrect format of _cfg/simulator.cfg_ could raise this error. If your operating system is Windows and you have set _git config --global core.autocrlf true_ , when you clone this repo, git will automatically add _CR_ to _cfg/simulator.cfg_. This will lead to your error in Linux of the docker container. 
So please change _cfg/simulator.cfg_ from CRLF to LF after cloning this repo.

**Comment by BruceChen2017** [comment]
@wrnge Thanks!

**Comment by BruceChen2017** [comment]
@wrnge Maybe you can add this problem in the readme.

**Comment by zhyliu00** [comment]
Thanks for your suggestion. We have added this issue to reame.
